# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "iwlwifi"];
  boot.extraModulePackages = [  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8ed06cc2-dc94-4233-9d90-440c59f1bd34";
      fsType = "ext4";
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3fe9a756-16da-4424-a6fc-4c63b8cf9ade";
      fsType = "ext4";
    };
  fileSystems."/boot/efi" =
   { device = "/dev/disk/by-uuid/4C39-1764";
   };

  swapDevices = [ ];
  nixpkgs.config.pulseaudio = true;
  hardware.enableAllFirmware = true;
  hardware.pulseaudio.enable = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
